#!/usr/bin/env python3
"""Write one Microsoft Forms build sheet per role from site/data/surveys.json.

Output: docs/surveys/<role-id>.md, one per role. Each question title starts with its
ID in brackets, e.g. "[Q07] ...", so answers exported from Forms can be matched back
to the question bank. Run again whenever surveys.json changes.

    python3 scripts/export_forms.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SURVEYS = json.loads((ROOT / "site" / "data" / "surveys.json").read_text())
OUT = ROOT / "docs" / "surveys"

FORMS_TYPE = {
    "rating": "Rating (5 levels, Number symbol)",
    "nps": "Net Promoter Score",
    "number": "Text, with Restrictions set to Number",
    "single": "Choice",
    "multi": "Choice, with Multiple answers on",
    "rank": "Ranking",
    "matrix": "Likert",
    "text": "Text",
}


def scale_text(key):
    sc = SURVEYS["scales"][key]
    labels = sc["labels"]
    if len(labels) == sc["max"] - sc["min"] + 1:
        return "; ".join(f"{sc['min'] + i} = {l}" for i, l in enumerate(labels))
    return f"{sc['min']} to {sc['max']} ({', '.join(labels)})"


def question_md(n, q):
    t = q["type"]
    kind = FORMS_TYPE[t] + (", Long answer on" if t == "text" and q.get("long") else "")
    lines = [f"**{n}. [{q['id']}] {q['text']}**", ""]
    lines.append(f"- Forms type: {kind}")
    lines.append(f"- Required: {'yes' if q['required'] else 'no'}")
    if q.get("help"):
        lines.append(f"- Subtitle: {q['help']}")
    if t == "number":
        lines.append(f"- Restriction: Between {q.get('min', 0)} and {q.get('max', '')}. Subtitle: answer in {q['unit']}.")
    if t == "rating":
        sc = SURVEYS["scales"][q["scale"]]
        lines.append(f"- Labels: low end \"{sc['labels'][0]}\", high end \"{sc['labels'][-1]}\" ({scale_text(q['scale'])})")
    if t == "nps":
        lines.append("- Labels: keep the Forms defaults (0 = Not at all likely, 10 = Extremely likely)")
    if t == "multi" and q.get("maxPick"):
        lines.append(f"- Limit: up to {q['maxPick']} choices (keep \"Pick up to {q['maxPick']}\" in the title; Forms may not enforce it)")
    if t in ("single", "multi", "rank"):
        lines.append("- Options (enter in this order):" if t != "rank" else "- Options (people drag these into order):")
        lines += [f"    - {o}" for o in q["options"]]
    if t == "matrix":
        lines.append(f"- Options (columns): {', '.join(SURVEYS['scales'][q['scale']]['labels'])}")
        lines.append("- Statements (rows):")
        lines += [f"    - {r}" for r in q["rows"]]
    return "\n".join(lines) + "\n"


def role_md(role):
    qs = [q for q in SURVEYS["questions"] if role["id"] in q["roles"]]
    order = {s["id"]: i for i, s in enumerate(SURVEYS["sections"])}
    qs.sort(key=lambda q: order[q["section"]])  # stable: keeps question order within a section
    group = next(g["label"] for g in SURVEYS["groups"] if g["id"] == role["group"])
    out = [
        f"# Staff questionnaire: {role['label']}",
        "",
        f"Group: {group} · Role ID: `{role['id']}` · {len(qs)} questions · about {role['estimatedMinutes']} minutes",
        "",
        "_Generated by `scripts/export_forms.py` from `site/data/surveys.json`. Do not edit by hand. See [README](README.md) for how to build the form._",
        "",
        "## Form title and description",
        "",
        f"- Title: New commercial loan system: {role['label']} survey",
        f"- Description: {SURVEYS['intro']} {role['intro']}",
        f"- Thank-you message (Settings > Customize thank you message): {SURVEYS['closing']}",
        "",
    ]
    n, current = 0, None
    for q in qs:
        if q["section"] != current:
            current = q["section"]
            sec = next(s for s in SURVEYS["sections"] if s["id"] == current)
            out += [f"## Section: {sec['title']}", ""]
            if sec.get("intro"):
                out += [f"_Section subtitle: {sec['intro']}_", ""]
        n += 1
        out.append(question_md(n, q))
    return "\n".join(out)


def readme(roles):
    rows = "\n".join(
        f"| [{r['label']}]({r['id']}.md) | `{r['id']}` | {sum(r['id'] in q['roles'] for q in SURVEYS['questions'])} | {r['estimatedMinutes']} |"
        for r in roles)
    return f"""# Staff questionnaires

One survey per role, built from the shared question bank in `site/data/surveys.json`
({len(SURVEYS['questions'])} questions). Every survey shares a common core (tenure, satisfaction, likelihood to recommend,
pain points, one thing to change, willingness to help) so answers can be compared across roles, plus questions
specific to the role.

**The project site is display-only.** It shows the questions as part of the project plan. Microsoft Forms collects
the answers. Loading the answers back into the site is optional (see the last section).

| Survey | Role ID | Questions | Minutes |
| --- | --- | --- | --- |
{rows}

These files are generated. To change a question, edit `site/data/surveys.json`, then run:

```sh
python3 scripts/export_forms.py
python3 scripts/validate.py
```

## Building a form in Microsoft Forms

1. Go to forms.office.com and choose **New Form**. Use the title, description and thank-you message from the
   top of the role's sheet.
2. Add a **section** for each "Section:" heading in the sheet, with the subtitle if one is given.
3. Add each question in order. **Copy the title exactly, including the `[Q##]` prefix.** The prefix is how answers are
   matched back to the question bank; changing it breaks the import.
4. Use the Forms type listed under each question:
   - **Choice**: one answer, or turn on **Multiple answers** for "select all" and "pick up to" questions.
   - **Text** with **Restrictions > Number** (or **Between**) for number questions. Put the unit in the subtitle.
   - **Text** with **Long answer** for open comments.
   - **Rating**: 5 levels, Number symbol, with the end labels given.
   - **Likert**: enter the scale labels as options (columns) and the statements as rows.
   - **Ranking**: enter the options; people drag them into order.
   - **Net Promoter Score**: keep the 0-10 defaults.
5. Turn **Required** on where the sheet says yes.
6. Preview on a phone as well as a desktop before sending.

A quick way to make the eight forms: build one survey completely, then use **Duplicate** in Forms and delete or add
questions for the next role. Check each duplicate against its sheet.

### Recommended settings

- **Who can fill out this form:** Only people in my organization.
- **Record name:** off, so responses are anonymous. Say so in the description (it already does).
- **One response per person:** optional. It needs sign-in and prevents duplicates; with Record name off, names
  are still not stored.
- **Start date / End date:** set an end date about two weeks after sending.
- **Shuffle questions:** off. The order matters.
- The last question asks whether people want to help. Send a separate sign-up link (or ask managers) to collect
  names, so survey answers stay anonymous.

## Getting the answers out

In Forms, open **Responses > Open results in Excel** (or **Download a copy**). Each form gives one workbook.
Forms writes one column per question titled with the full question text (so the `[Q##]` prefix is kept),
multiple-choice and ranking answers as text separated by semicolons, and one column per row for Likert questions.

## Optional: loading answers into the site

`scripts/import_responses.py` reads one export and appends its rows to `site/data/survey-responses.json`
for analysis. It is not needed to run the survey.

```sh
# .xlsx needs openpyxl (pip install openpyxl); otherwise save the sheet as CSV (UTF-8) from Excel first
python3 scripts/import_responses.py --role credit-analyst "Credit Analysts survey.xlsx"
python3 scripts/import_responses.py --role cla cla-responses.csv --dry-run   # check without writing
python3 scripts/validate.py
```

- `--role` must be one of the role IDs in the table above; use the file for that role's form.
- Columns without a `[Q##]` prefix are ignored, except the Forms **ID** and **Completion time** columns.
- Re-importing the same file is safe: rows already imported (same role and Forms response ID) are skipped.
- Answers become: numbers for rating, NPS and number questions; text for single choice and open questions;
  lists for multiple choice and ranking (in ranked order); and `{{statement: score}}` for Likert questions.
  Likert labels such as "Agree" are converted to their score on the scale.
- Anything that cannot be matched is reported as a warning and left out, not guessed.
"""


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    roles = SURVEYS["roles"]
    for r in roles:
        (OUT / f"{r['id']}.md").write_text(role_md(r))
    (OUT / "README.md").write_text(readme(roles))
    print(f"wrote {len(roles)} survey sheets and README.md to {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
